version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "canary-demo-v2"
s3_bucket = ""
s3_prefix = "canary-demo-v2"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=canary-demo-v2 Environment=dev"
confirm_changeset = false
fail_on_empty_changeset = false